version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "4000:9000"
    volumes:
      - /home/aatit/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  
