version: '3'

services:
  #  frontend:
  #    build: ./frontend
  #    ports:
  #      - "3000:3000"
  #
  #  backend:
  #    build: ./backend
  #    ports:
  #      - "3001:3001"
  #
  #  chatapp:
  #    build: ./chat-app/frontend
  #    ports:
  #      - "3002:3002"
  #
  
  #  homepage:
  #    image: ghcr.io/gethomepage/homepage:latest
  #    container_name: homepage
  #    ports:
  #      - 3000:3000
  #    volumes:
  #      - /home/aatit/data/homepage:/app/config # Make sure your local config directory exists
  #      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
  #    environment:
  #      PUID: $PUID
  #      PGID: $PGID

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "4000:9000"
    volumes:
      - /home/aatit/data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

      #  qbittorrent:
      #    image: lscr.io/linuxserver/qbittorrent:latest
      #    container_name: qbittorrent
      #    environment:
      #      - PUID=1000
      #      - PGID=1000
      #      - TZ=Etc/UTC
      #      - WEBUI_PORT=8080
      #      - TORRENTING_PORT=6881
      #    volumes:
      #      - /home/aatit/data/qbittorrent/config:/config
      #      - /home/aatit/data/qbittorrent/downloads:/downloads
      #      - /home/aatit/data/jellyfin/tvseries:/tv
      #      - /home/aatit/data/jellyfin/movies:/movies
      #    ports:
      #      - 8080:8080 # Web UI port
      #      - 6881:6881 # Torrent port
      #      - 6881:6881/udp # Torrent UDP port
      #    restart: unless-stopped
      #
      #  prowlarr:
      #    image: lscr.io/linuxserver/prowlarr:latest
      #    container_name: prowlarr
      #    environment:
      #      - PUID=1000
      #      - PGID=1000
      #      - TZ=Etc/UTC
      #    volumes:
      #      - /home/aatit/data/prowlarr/config:/config
      #    ports:
      #      - 9696:9696
      #    restart: unless-stopped
      #
      #  sonarr:
      #    image: lscr.io/linuxserver/sonarr:latest
      #    container_name: sonarr
      #    environment:
      #      - PUID=1000
      #      - PGID=1000
      #      - TZ=Etc/UTC
      #    volumes:
      #      - /home/aatit/data/sonarr/data:/config
      #      - /home/aatit/data/jellyfin/tvseries:/tv #optional
      #       #- /path/to/downloadclient-downloads:/downloads #optional
      #    ports:
      #      - 4002:8989
      #    restart: unless-stopped
      #
      #  radarr:
      #    image: lscr.io/linuxserver/radarr:latest
      #    container_name: radarr
      #    environment:
      #      - PUID=1000
      #      - PGID=1000
      #      - TZ=Etc/UTC
      #    volumes:
      #      - /home/aatit/data/radarr/data:/config
      #      - /home/aatit/data/jellyfin/movies:/movies #optional
      #    ports:
      #      - 4003:7878
      #    restart: unless-stopped
      #
      #  jellyfin:
      #    image: lscr.io/linuxserver/jellyfin:latest
      #    container_name: jellyfin
      #    environment:
      #      - PUID=1000
      #      - PGID=1000
      #      - TZ=Etc/UTC
      #        # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
      #        
      #    volumes:
      #      - /home/aatit/data/jellyfin/config:/config
      #      - /home/aatit/data/jellyfin/tvseries:/data/tvshows
      #      - /home/aatit/data/jellyfin/movies:/data/movies
      #
      #    ports:
      #      - 8096:8096
      #      - 8920:8920 #optional
      #      - 7359:7359/udp #optional
      #      - 1900:1900/udp #optional
      #    restart: unless-stopped
      
      #  nginx:
      #    build: ./nginx
      #    ports:
      #      - "80:80"
      #      - "443:443"
      #
      #    depends_on:
      #      - frontend
      #      - backend
      #      - chatapp
      #      - portainer
      #      - jellyfin
