services:
  nginx:
    image: nginx:latest
    container_name: nginx-wildcard
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/aatit/applications/services/nginx/default1.conf:/etc/nginx/conf.d/default.conf  # Mount custom Nginx config
      - /home/aatit/applications/services/nginx/ssl:/etc/letsencrypt
      - /home/aatit/applications/services/certbot/www:/var/www/certbot  # Webroot directory for Certbot

    restart: unless-stopped
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /home/aatit/applications/services/nginx/ssl:/etc/letsencrypt
      - /home/aatit/applications/services/certbot/www:/var/www/certbot  # Same webroot directory
    command: certonly --webroot --webroot-path=/var/www/certbot --email aatitkarki12345@gmail.com --agree-tos --no-eff-email -d sureshk.com.np -d *.sureshk.com.np
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    networks:
      - app-network

networks:
  app-network:
    external: true 