version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-wildcard
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/aatit/applications/services/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount custom Nginx config
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true 