# Secrets are not here but stored on my macbook
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/aatit/data/qbittorrent/config:/config
      - /home/aatit/data/qbittorrent/downloads:/downloads
      # - /media/devmon/STORAGE/qbittorrent/downloads:/downloads
      - /media/devmon/STORAGE/jellyfin/tvseries:/tv
      - /media/devmon/STORAGE/jellyfin/movies:/movies
    ports:
      - 8080:8080 # Web UI port
      - 6881:6881 # Torrent port
      - 6881:6881/udp # Torrent UDP port
    restart: unless-stopped
    networks:
      - app-network

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 # optional
    volumes:
      - /home/aatit/data/jellyfin/config:/config
      # - /home/aatit/data/jellyfin/tvseries:/data/tvshows
      # - /home/aatit/data/jellyfin/movies:/data/movies
      - /home/aatit/data/qbittorrent/downloads:/data/tvshows
      # - /media/devmon/STORAGE/jellyfin/tvseries:/data/tvshows
      - /media/devmon/STORAGE/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 # optional
      - 7359:7359/udp # optional
      - 1900:1900/udp # optional
    restart: unless-stopped
    networks:
      - app-network

  ghost_blog:
    image: ghost:5-alpine
    restart: always
    container_name: ghost_blog
    environment:
      url: https://blog.sureshk.com.np  # Your domain
      mail__transport: SMTP
      mail__options__host: smtp.gmail.com
      mail__options__port: 587
      mail__options__auth__user: ${MAIL_AUTH_USER}
      mail__options__auth__pass: ${MAIL_OPTIONS_AUTH_PASS} 
      mail__from: ${MAIL_AUTH_USER}
      database__client: mysql
      database__connection__host: mysqldb
      database__connection__user: root
      database__connection__password: ${MYSQL_ROOT_PASSWORD}
      database__connection__database: ghost
    volumes:
      - ~/data/ghost:/var/lib/ghost/content 
    ports:
      - 4005:2368
    networks:
      - app-network

  mysqldb:
    image: mysql:8.0
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/data/mysql:/var/lib/mysql  # Change this to your actual path
    networks:
      - app-network

  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    hostname: raspberrypi-tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    security_opt:
      - apparmor:unconfined
    network_mode: "host" # Necessary for Tailscale to manage the network
    environment:
      - TS_AUTHKEY= ${TS_AUTHKEY} # Add your Tailscale auth key here
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
    restart: unless-stopped

# To create the network, run the following command:
# docker network create app-network
networks:
  app-network:
    external: true 
